if status --is-login
    # set these here
    set -gx XDG_CACHE_HOME "$HOME/.cache"
    set -gx XDG_CONFIG_HOME "$HOME/.config"
    set -gx XDG_DATA_HOME "$HOME/.local/share"

    set -gx ALTUSERXSESSION "$XDG_CACHE_HOME/X11/Xsession"
    set -gx BROWSER "firefox"
    set -gx CARGO_HOME "$XDG_DATA_HOME/cargo"
    set -gx EDITOR "nvim" # ed users cope
    set -gx ERRFILE "$XDG_CACHE_HOME/X11/xsession-errors"
    set -gx ICEAUTHORITY "$XDG_CACHE_HOME/ICEauthority"
    set -gx GOPATH "$XDG_DATA_HOME/go"
    set -gx GTK2_RC_FILES "$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
    set -gx GNUPGHOME "$XDG_DATA_HOME/gnupg"
    set -gx LESSHISTFILE "-"
    set -gx LS_COLORS "$(vivid generate catppuccin-mocha)"
    set -gx MANPAGER "bat"
    set -gx NETHACKOPTIONS "$XDG_CONFIG_HOME/nethack/nethackrc"
    set -gx NPM_CONFIG_USERCONFIG "$XDG_CONFIG_HOME/npm/npmrc"
    set -gx PAGER "bat"
    set -gx QT_QPA_PLATFORMTHEME "qt5ct"
    set -gx RUSTUP_HOME "$XDG_DATA_HOME/rustup"
    set -gx TERMINAL "kitty"
 	set -gx TEXMFHOME "$XDG_DATA_HOME/texmf"
    set -gx TEXMFVAR "$XDG_CACHE_HOME/texlive/texmf-var"
    set -gx USERXSESSION "$XDG_CACHE_HOME/X11/xsession"
    set -gx USERXSESSIONRC "$XDG_CACHE_HOME/X11/xsessionrc"
    set -gx VISUAL "nvim"
    set -gx WGETRC "$XDG_CONFIG_HOME/wget/wgetrc"
    set -gx WINEPREFIX "$XDG_DATA_HOME/wine/prefix"
    set -gx XAUTHORITY "$XDG_RUNTIME_DIR/Xauthority"
    set -gx XINITRC "$XDG_CONFIG_HOME/X11/xinitrc"

    fish_add_path -p "$HOME/.local/bin" "$HOME/.local/share/cargo/bin" "$HOME/.local/share/cargo/bin/rustup"
end
